@TodoAPI_HostAddress = https://localhost:7079

GET {{TodoAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{TodoAPI_HostAddress}}/api/todoitems
Content-Type: application/json

{
   "name": "walk dog",
  "isComplete": true
}

###

GET {{TodoAPI_HostAddress}}/api/todoitems

###

@id=1
GET {{TodoAPI_HostAddress}}/api/todoitems/2

###

PUT {{TodoAPI_HostAddress}}/api/todoitems/1
Content-Type: application/json

{
  "id": 1,
  "name": "feed fish",
  "isComplete": false
}

###

DELETE {{TodoAPI_HostAddress}}/api/todoitems/2

###
